
repos:
    # precommit
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      description: Precommit checks
      hooks:
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: detect-private-key # detects the presence of private keys.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: trailing-whitespace # trims trailing whitespace.

    # isort
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
      - id: isort # sorts imports
        args: ["--profile", "black"]

    # black
    - repo: https://github.com/psf/black
      rev: 23.7.0
      hooks:
        - id: black
          args:
            - --line-length=120
          language_version: python3

    # flake8
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
        - id: flake8
          args:
            - "--max-line-length=120" # making isort line length compatible with black

            # - "--max-complexity=18"
            # - "--select=B,C,E,F,W,T4,B9"

            # these are errors that will be ignored by flake8
            # check out their meaning here
            # https://flake8.pycqa.org/en/latest/user/error-codes.html
            # - "--ignore=E203,E266,E501,W503,F403,F401,E402,E722"
